### ISSUE TITLE
Fix email truncation on Android

### ISSUE THREAD

**Issue by mattg95** [mattg95/07_campaign#123]
Feedback from a user:

One flaw which could be urgent is that the email to MP gets truncated for some reason? See below.

I'm on an Android smartphone if that's relevant.

---------- Forwarded message ---------
From: [...] <...>
Date: Tue, 16 Feb 2021, 13:41
Subject: Proposed reduction in aid budget
To: <david.duguid.mp@parliament.uk>

Dear David Duguid,
I feel frustrated that the government is not delivering on its manifesto promise to dedicate 0.7 percent of national income to overseas development spending. I wanted to clarify a potential misunderstanding here - as the aid budget is a percentage of UK GDP, it reduces automatically when the UK GDP shrinks. It is a weak justification to say that the UK is worse off right now and so it is ok to reduce the aid budget. Please tell me that you will vote against this? Or at least tell me that you will make absolutely sure that this will be temporary, and that the temporariness is written into law.

Hundreds of millions of people across the�

**Comment by anitawoodruff** [comment]
I tried to reproduce this by generating an email on Android and then copying it to clipboard and pasting into gmail, but it pasted just fine. @mattg95 can we contact this user & ask them:

a. did they use the 'copy' button on the site to copy this unedited?
b. which email application did they paste this into?

and if they want to be extra helpful:
c. what version of Android & what model phone are they on?
d. does it always truncate if they try it again?

**Comment by anitawoodruff** [comment]
Answers from the user via Sanjay:

> a. The 'send email' button
> 
> b. Opened in Gmail
> 
> c. Android 10 on OnePlus 7T
> 
> d. I just tried it and did not have the same problem. 

given this, I think we should Close this as Not Reproducible. If we get more reports we can always reopen it.
