### ISSUE TITLE
Mp+email not generating/disappearing on Android after submitting

### ISSUE THREAD

**Issue by anitawoodruff** [mattg95/07_campaign#125]
On Android, *sometimes* after submitting, it says 'scroll down to see your email', but if you wait a couple of seconds you see **there is no email generated further down**, & there's also no 'Could not retrieve MP' box - it just takes you back to the start screen. See screen recording:

https://user-images.githubusercontent.com/1918555/108428299-4072d500-7236-11eb-82b9-162ccc7226ff.mp4

Or sometimes you do see an mp generated but then as you scroll down it disappears.

And sometimes it works just fine.

**Comment by anitawoodruff** [comment]
unassigning from myself in case someone else can pick this up tomorrow, otherwise i can take another look on Sat

**Comment by mattg95** [comment]
I had not put set up the webhook in Typeform admin panel for the staging site, so the generated email wasn't comping through. Sorry @anitawoodruff my mistake, thanks for pointing this out though as it means the staging site now works as it shouls

**Comment by anitawoodruff** [comment]
pretty sure I also saw this at the prod site, though would have to do more testing to be sure..
