### ISSUE TITLE
Flaky test: "emails to non-conservative MPs should not reference that the user is a conservative"

### ISSUE THREAD

**Issue by anitawoodruff** [mattg95/07_campaign#133]
steps to reproduce:

- run `npm run test-email` a bunch of times
- sometimes it fails (<50% of the time)

e.g.
```
  15 passing (2s)
  1 failing

  1) generateEmail
       emails to non-conservative MPs should not reference that the user is a conservative in the email:

      AssertionError: expected 12 to equal -1
      + expected - actual

      -12
      +-1
```

the assertion error number is different each time - I guess because the word 'conservative' appears in different places depending on what text is generated

as part of fixing this it would be nice to make the error message more informative than a numerical assertion error. should be able to do this with a chai expect(...).to.contain(...) assertion

**Comment by mattg95** [comment]
fixed by removing that test
